version: '3.1'

services:

  fi-hg-repository-mysql:
    restart: "unless-stopped"
    container_name: fi-hg-repository-mysql
    platform: linux/amd64
    image: "fi-hg-repository-mysql:latest"
    cap_add:
    - SYS_NICE  # CAP_SYS_NICE
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MYSQL_IMAGE: 'mysql:8'
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "fcRmzTX7ra9cIwGBfWn914GNjS7FmMpt"
      MYSQL_DATABASE: "hg"
      MYSQL_USER: "hg"
      MYSQL_PASSWORD: "rxPe4XHbonLeHwjvKdq9R9aDWf1xiUje"
    volumes:
    - "./volumes/mysql-data:/var/lib/mysql"

